version: '3'

services:
docker-mysql:
image: mysql:latest
spring-boot-jpa-docker-webapp:
depends_on:
  - docker-mysql
ports:
  - 8080:8080
environment:
  - DATABASE_HOST=10.40.0.2
  - DATABASE_USER=root
  - DATABASE_PASSWORD=NNYp9XM4zkDnZvn5
  - DATABASE_NAME=cb_testing
  - DATABASE_PORT=32048